AWSTemplateFormatVersion: 2010-09-09
Description: Root Stack for AWS Amplify Console
Parameters:
  AppName:
    Type: String
  DeploymentBucketName:
    Description: Name of the common deployment bucket provided by the parent stack
    Type: String
    Default: DeploymentBucket
  AuthRoleName:
    Type: String
    Default: AuthRoleName
  UnauthRoleName:
    Type: String
    Default: UnauthRoleName
  Environment:
    Type: String
    Description: Environment name
  AppUrl:
    Type: String
    Description: App's URL
Resources:
  DeploymentBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref DeploymentBucketName
  AuthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref AuthRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
  UnauthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref UnauthRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
Outputs:
  Region:
    Description: CloudFormation provider root stack Region
    Value: !Ref 'AWS::Region'
    Export:
      Name: !Sub '${AWS::StackName}-Region'
  StackName:
    Description: CloudFormation provider root stack ID
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub '${AWS::StackName}-StackName'
  StackId:
    Description: CloudFormation provider root stack name
    Value: !Ref 'AWS::StackId'
    Export:
      Name: !Sub '${AWS::StackName}-StackId'
  DeploymentBucketName:
    Description: CloudFormation provider root stack deployment bucket name
    Value: !Ref DeploymentBucketName
    Export:
      Name: !Sub '${AWS::StackName}-DeploymentBucketName'
  AuthRoleArn:
    Value: !GetAtt 
      - AuthRole
      - Arn
  UnauthRoleArn:
    Value: !GetAtt 
      - UnauthRole
      - Arn
  AuthRoleName:
    Value: !Ref AuthRole
  UnauthRoleName:
    Value: !Ref UnauthRole
