AWSTemplateFormatVersion: 2010-09-09
Description: Root Stack for AWS Amplify Console
Parameters:
  DeploymentBucketName:
    Description: Name of the common deployment bucket provided by the parent stack
    Type: String
    Default: DeploymentBucket
  AuthRoleName:
    Type: String
    Default: AuthRoleName
  UnauthRoleName:
    Type: String
    Default: UnauthRoleName
  AppName:
    Type: String
  Environment:
    Type: String
    Description: Environment name
Resources:
  DeploymentBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref DeploymentBucketName
  AuthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref AuthRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
  UnauthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref UnauthRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
  Auth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ['/', ['https://s3.amazonaws.com', !Ref DeploymentBucketName, 'amplify-cfn-templates/auth/backend-auth.yml']]
      Parameters:
        appName: !Ref AppName
        resourceNameTruncated: !Select  [0, !Split ['-', !Ref AppName]]
        autoVerifiedAttributes: email
        mfaConfiguration: 'OFF'
        mfaTypes: SMS Text Message
        smsAuthenticationMessage: Your authentication code is {####}
        smsVerificationMessage: Your verification code is {####}
        emailVerificationSubject: Your verification code
        emailVerificationMessage: Your verification code is {####}
        defaultPasswordPolicy: false
        passwordPolicyMinLength: 8
        passwordPolicyCharacters: ''
        requiredAttributes: email
        userpoolClientGenerateSecret: true
        userpoolClientRefreshTokenValidity: 30
        userpoolClientWriteAttributes: email
        userpoolClientReadAttributes: email
        userpoolClientSetAttributes: false
        authSelections: userPoolOnly
        authRoleArn:
          Fn::GetAtt:
          - AuthRole
          - Arn
        unauthRoleArn:
          Fn::GetAtt:
          - UnauthRole
          - Arn
        useDefault: manual
        usernameAttributes: email
        userPoolGroups: false
        adminQueries: false
        triggers: "{}"
        hostedUI: true
        authProvidersUserPool: ''
        hostedUIProviderMeta: "[]"
        oAuthMetadata: '{"AllowedOAuthFlows":["implicit"],"AllowedOAuthScopes":["phone","email","openid","profile","aws.cognito.signin.user.admin"],"CallbackURLs":["http://localhost:3000/"],"LogoutURLs":["http://localhost:3000/"]}'
        userPoolGroupList: ''
        serviceName: Cognito
        parentStack:
          Ref: AWS::StackId
        permissions: ''
        dependsOn: ''
        hostedUIProviderCreds: "[]"
        env: !Ref Environment
Outputs:
  Region:
    Description: CloudFormation provider root stack Region
    Value: !Ref 'AWS::Region'
    Export:
      Name: !Sub '${AWS::StackName}-Region'
  StackName:
    Description: CloudFormation provider root stack ID
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub '${AWS::StackName}-StackName'
  StackId:
    Description: CloudFormation provider root stack name
    Value: !Ref 'AWS::StackId'
    Export:
      Name: !Sub '${AWS::StackName}-StackId'
  DeploymentBucketName:
    Description: CloudFormation provider root stack deployment bucket name
    Value: !Ref DeploymentBucketName
    Export:
      Name: !Sub '${AWS::StackName}-DeploymentBucketName'
  AuthRoleArn:
    Value: !GetAtt 
      - AuthRole
      - Arn
  UnauthRoleArn:
    Value: !GetAtt 
      - UnauthRole
      - Arn
  AuthRoleName:
    Value: !Ref AuthRole
  UnauthRoleName:
    Value: !Ref UnauthRole
  AuthTemplateURL:
    Value: !Join ['/', ['https://s3.amazonaws.com', !Ref DeploymentBucketName, 'amplify-cfn-templates/auth/backend-auth.yml']]  
  AuthStackName:
    Value: !GetAtt
      - Auth
      - Outputs.StackName

